---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: secret-cont 
      image: nginx
      envFrom:
        - secretRef:
            name: my-secret
      ports:
        - containerPort: 80